package pojo;
// Generated Mar 28, 2014 6:28:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Embeddable;

/**
 * AdminsActionsId generated by Mahmoud Eltaieb
 */
@Embeddable 
public class AdminsActionsId  implements java.io.Serializable {


     private int adminId;
     private int employeeId;
     private Date actionDate = new Date();

    public AdminsActionsId() {
    }

    public AdminsActionsId(int adminId, int employeeId) {
       this.adminId = adminId;
       this.employeeId = employeeId;
       
    }
   
    public int getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }


 
   


}


