package pojo;
// Generated Mar 28, 2014 6:28:10 PM by Hibernate Tools 3.2.1.GA

import DAOS.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import utils.Constants;

/**
 * Garage generated by hbm2java
 */
@Entity
public class Garage implements java.io.Serializable {

    @Id
    @GeneratedValue
    private Integer garageId;
    private String title;
    private String country;
    private String city;
    private double lon;
    private double lat;
    private int slots;
    @OneToOne(orphanRemoval = true, fetch = FetchType.EAGER)
    private Map map;
    @OneToMany(mappedBy = "garage", orphanRemoval = true)
    @ElementCollection(fetch = FetchType.LAZY)
    private Collection< Employees> employees = new ArrayList< >();
    @OneToMany(mappedBy = "garage", orphanRemoval = true)
    @ElementCollection(fetch = FetchType.EAGER)
    private Collection< GarageDoors> garageDoors = new ArrayList< >();
    @OneToMany(mappedBy = "garage", orphanRemoval = true)
    @ElementCollection(fetch = FetchType.EAGER)
    private Collection< GarageStatus> garageStatus = new ArrayList< >();


    public int getSlots() {
        return slots;
    }

    public void setSlots(int slots) {
        this.slots = slots;
    }

    private double hourRateInRush;
    private double hourRateOutOfRush;

    public double getHourRateInRush() {
        return hourRateInRush;
    }

    public void setHourRateInRush(double hourRateInRush) {
        this.hourRateInRush = hourRateInRush;
    }

    public double getHourRateOutOfRush() {
        return hourRateOutOfRush;
    }

    public void setHourRateOutOfRush(double hourRateOutOfRush) {
        this.hourRateOutOfRush = hourRateOutOfRush;
    }

    
    public Garage() {
        this.employees = new HashSet<Employees>();
    }

    public Garage(int id) {
        this.employees = new HashSet<Employees>();
        garageId = id;
    }

    public Garage(Map map, String title, int slots, int lon, int lat) {
        this.employees = new HashSet<Employees>();

        this.map = map;
        this.title = title;

        this.lon = lon;
        this.lat = lat;
    }

    public Garage(Map map, String title, String country, String city, double lon, double lat) {
        this.employees = new HashSet<Employees>();

        this.map = map;
        this.title = title;
        this.country = country;
        this.city = city;

        this.lon = lon;
        this.lat = lat;

    }

    public Garage(String title, String country, String city, double hourRateInRush, double hourRateOutOfRush, int slots, int doors, double lat, double lon) {
        this.employees = new HashSet<Employees>();

        this.title = title;
        this.country = country;
        this.city = city;
        this.lon = lon;
        this.lat = lat;
        this.hourRateInRush = hourRateInRush;
        this.hourRateOutOfRush = hourRateOutOfRush;

    }

    public Collection<GarageStatus> getGarageStatus() {
        return garageStatus;
    }

    public void setGarageStatus(Collection<GarageStatus> garageStatus) {
        this.garageStatus = garageStatus;
    }

    public Collection<Employees> getEmployees() {
        return employees;
    }

    public void setEmployees(Collection<Employees> employees) {
        this.employees = employees;
    }

    public Collection<GarageDoors> getGarageDoors() {
        return garageDoors;
    }

    public void setGarageDoors(Collection<GarageDoors> garageDoors) {
        this.garageDoors = garageDoors;
    }

    public Integer getGarageId() {
        return this.garageId;
    }

    public void setGarageId(Integer garageId) {
        this.garageId = garageId;
    }

    public Map getMap() {
        return this.map;
    }

    public void setMap(Map map) {
        this.map = map;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public double getLon() {
        return this.lon;
    }

    public void setLon(double lon) {
        this.lon = lon;
    }

    public double getLat() {
        return this.lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public Collection< Employees> getEmployeeses() {
        return this.employees;
    }

    public void setEmployeeses(Collection< Employees> employees) {
        this.employees = employees;
    }

}
