package pojo;
// Generated Mar 28, 2014 6:28:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Roles generated by hbm2java
 */
@Entity
public class Roles implements java.io.Serializable {

    @Id
    private int roleId;
    private String roleName;
    private String description;
    @ElementCollection(fetch = FetchType.LAZY)
    @OneToMany(mappedBy = "roles" )
    private Collection<Employees> employeeses = new HashSet<Employees>();

    public Roles(int roleId) {
        this.roleId = roleId;
    }

    public Roles() {
    }

    public Roles(int roleId, String roleName, String description) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.description = description;

    }

    public Roles(int roleId, String roleName, String description, Set employeeses) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.description = description;
        this.employeeses = employeeses;
    }

    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Collection<Employees> getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Collection<Employees> employeeses) {
        this.employeeses = employeeses;
    }
}
