package pojo;
// Generated Mar 28, 2014 6:28:10 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

    @Id
    @GeneratedValue
    private int userId;
    private String userName;
    private String firstName;
    private String lastName;
    private String email;
    private String password;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date birthDate;
    private String gender;
    private String phone;
    @OneToMany(mappedBy = "user")
    private Collection<Visit> visits;

    public Users() {
    }
    public Users(int id)
    {
    
        this.userId= id;
    }
    public Users(int id, String userName, String email, String password) {
        this.userId = id;
        this.userName = userName;
        this.email = email;
        this.password = password;

    }

    public Users(String userName, String email, String password) {
        this.userName = userName;
        this.email = email;
        this.password = password;
    }

    public Users(String firtName, String lastName, String userName, String email, String password, String birthDate, String gender, String phone) {
        this.userName = userName;
        this.email = email;
        this.password = password;

    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Collection<Visit> getVisits() {
        return visits;
    }

    public void setVisits(Collection<Visit> visits) {
        this.visits = visits;
    }
}
